# frozen_string_literal: true
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'

gem 'fluent-logger', "~> 0.4.3"

gem 'dotenv'
gem 'contentful-management'

gem 'pry'
gem 'pry-byebug'
